### PR TITLE
[CS-1848] Add browser flow option

### PR DESCRIPTION
**Pull request by nikolack**
Enable browser flow for AuthorizingPaymentActivity. This will open authorize_url in browser, instead of in-app.

CS Ticket: https://opn-ooo.atlassian.net/browse/CS-1804
https://opn-ooo.atlassian.net/browse/CS-1848

### CODE REVIEW

**Review by tookaa2 — APPROVED** [review]

**Comment by aashishgurung** [comment]
Can you please include the Jira ticket?

**Comment by nikolack** [comment]
@aashishgurung  I don't have the Jira ticket. @tookaa2  can you please provide?

**Comment by tookaa2** [comment]
@aashishgurung @nikolack we have this ticket which also links to Engagement's ticket
https://opn-ooo.atlassian.net/browse/CS-1804

**Comment by tookaa2** [comment]
here is the ticket @aashishgurung @nikolack
https://opn-ooo.atlassian.net/browse/CS-1846

**Review by new4762 — APPROVED** [review]

**Review by aashishgurung — APPROVED** [review]

**Comment by nuxzero** [comment]
Not sure, do we really want to support open external browser because they can implement by their own without using the SDK. However, Opening the external browser might required the app to support deeplink in order to redirect back to the app.

**Comment by nikolack** [comment]
@nuxzero not sure what could be the alternative solution. From the docs it seems like Bangkok bank app needs to whitelist app in order to navigate there using `startActivityForResult`

**Review by kan98 — APPROVED** [review]

**Comment by nikolack** [comment]
@nuxzero I think the solution you proposed today (to check the authorize URL and if it belongs to bangkok bank, open browser). This way there is no need for merchant to make any change to their app. It will affect all merchants using our app though.

**Pull request closed without merging**
