### PR TITLE
T20177 - Support new source types

### PR DESCRIPTION
**Pull request by nuxzero**
**1. Objective**

To support creating a source with new source types **PayNow** and **PromptPay**.

**2. Description of change**

In this PR add new source types **PayNow** and **PromptPay**. Also, add new properties `zeroInterestInstallments` and `scannableCode` to **Source** object.

**3. Quality assurance**

When create a source with new source type should receive success response.

**4. Operations impact**

N/A

**5. Business impact**

N/A

**6. Priority of change**

Normal

### CODE REVIEW

**Comment by keeratita** [comment]
1) I'm not sure that this attribute should be `device_id` instead of `id` krub? [Reference Object](https://github.com/omise/omise-android/blob/T20177-support-new-source-type/sdk/src/main/java/co/omise/android/models/References.kt#L26)

```
"references": {
    "expires_at": "2020-03-31T07:32:18.621Z",
    "device_id": "string",
    "customer_amount": 0,
    "customer_currency": "string",
    "customer_exchange_rate": 0,
    "omise_tax_id": "string",
    "reference_number_1": "string",
    "reference_number_2": "string",
    "barcode": "string",
    "payment_code": "string",
    "va_code": "string"
  },
```

**Comment by nuxzero** [comment]
The `id` field is base of every models. So, I think the `device_id` is a new field.

**Comment by nuxzero** [comment]
@keeratita I'll update this model in future PR. Do you have anything else?

**Comment by keeratita** [comment]
> @keeratita I'll update this model in future PR. Do you have anything else?

@nuxzero no krub. thanks a lot.

**Comment by testyfruit** [comment]
Hey
I verified this one. It looks okay for me. 
My test cases are [here](https://docs.google.com/spreadsheets/d/1I5GcaidChvcNTB4K47bsO-zqZDLz2kKKRX9F3t3fTbM/edit?usp=sharing).
`qa:ok`

**Pull request merged**
